# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qX7SSV2U2ZgxJme9sQUTbvra202ArJFj
"""


# archivo: seguimiento_pedidos.py
import streamlit as st
import pandas as pd
import datetime

# Cargar datos
try:
    pedidos = pd.read_csv("pedidos.csv")
except FileNotFoundError:
    pedidos = pd.DataFrame(columns=["ID", "Solicitante", "Descripción", "Estado", "Historial"])

# Función para guardar los datos
def guardar_pedidos(df):
    df.to_csv("pedidos.csv", index=False)

# Título
st.title("📦 Seguimiento de Pedidos - Proveeduría")

# Sección para agregar pedido
st.header("📝 Nuevo Pedido")
with st.form("form_pedido"):
    id_pedido = st.text_input("ID del Pedido")
    solicitante = st.text_input("Nombre del solicitante")
    descripcion = st.text_area("Descripción del pedido")
    if st.form_submit_button("Agregar"):
        nuevo_pedido = {
            "ID": id_pedido,
            "Solicitante": solicitante,
            "Descripción": descripcion,
            "Estado": "Solicitado",
            "Historial": f"{datetime.date.today()} - Pedido creado por {solicitante}"
        }
        pedidos = pedidos.append(nuevo_pedido, ignore_index=True)
        guardar_pedidos(pedidos)
        st.success("✅ Pedido agregado")

# Mostrar pedidos existentes
st.header("📋 Pedidos Existentes")
if not pedidos.empty:
    st.dataframe(pedidos[["ID", "Solicitante", "Descripción", "Estado"]])

    # Actualizar pedido
    st.subheader("🔄 Actualizar Estado")
    pedido_seleccionado = st.selectbox("Seleccionar ID de pedido", pedidos["ID"])
    nuevo_estado = st.selectbox("Nuevo estado", ["Cotización solicitada", "Esperando aprobación/pago", "En proceso de entrega", "Entregado", "Demora: proveedor / pago / gestión interna"])

    if st.button("Actualizar estado"):
        idx = pedidos[pedidos["ID"] == pedido_seleccionado].index[0]
        pedidos.at[idx, "Estado"] = nuevo_estado
        pedidos.at[idx, "Historial"] += f"\n{datetime.date.today()} - Estado actualizado a '{nuevo_estado}'"
        guardar_pedidos(pedidos)
        st.success("🔁 Estado actualizado correctamente")

    # Ver historial
    st.subheader("📜 Historial del Pedido")
    st.text(pedidos[pedidos["ID"] == pedido_seleccionado]["Historial"].values[0])
else:
    st.info("No hay pedidos registrados aún.")

